# Generated by Django 4.2.1 on 2023-12-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altrum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='altrum',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='altrum',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='altrum',
            index=models.Index(fields=['-time_create'], name='altrum_altr_time_cr_e54799_idx'),
        ),
    ]
