# Generated by Django 4.2.1 on 2023-12-09 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('altrum', '0005_category_altrum_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altrum',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='altrum.category'),
        ),
    ]
